export const business_types = [
  {
    id: 1,
    category: "Retail",
    subcategories: [
      { id: 1, name: "Clothing Stores" },
      { id: 2, name: "Electronics Stores" },
      { id: 3, name: "Grocery Stores" },
      { id: 4, name: "Bookstores" },
      { id: 5, name: "Specialty Shops" },
    ],
  },
  {
    id: 2,
    category: "Food & Beverage",
    subcategories: [
      { id: 6, name: "Restaurants" },
      { id: 7, name: "Cafes" },
      { id: 8, name: "Bars" },
      { id: 9, name: "Food Trucks" },
      { id: 10, name: "Bakeries" },
    ],
  },
  {
    id: 3,
    category: "Healthcare",
    subcategories: [
      { id: 11, name: "Hospitals" },
      { id: 12, name: "Dental Clinics" },
      { id: 13, name: "Pharmacies" },
      { id: 14, name: "Urgent Care Centers" },
      { id: 15, name: "Wellness Centers" },
    ],
  },
  {
    id: 4,
    category: "Finance",
    subcategories: [
      { id: 16, name: "Banks" },
      { id: 17, name: "Credit Unions" },
      { id: 18, name: "Accounting Firms" },
      { id: 19, name: "Insurance Agencies" },
      { id: 20, name: "Investment Firms" },
    ],
  },
  {
    id: 5,
    category: "Real Estate",
    subcategories: [
      { id: 21, name: "Real Estate Agencies" },
      { id: 22, name: "Property Management" },
      { id: 23, name: "Mortgage Brokers" },
      { id: 24, name: "Home Inspectors" },
      { id: 25, name: "Commercial Real Estate" },
    ],
  },
  {
    id: 6,
    category: "Education",
    subcategories: [
      { id: 26, name: "Schools" },
      { id: 27, name: "Tutoring Centers" },
      { id: 28, name: "Universities" },
      { id: 29, name: "Language Schools" },
      { id: 30, name: "Online Learning Platforms" },
    ],
  },
  {
    id: 7,
    category: "Technology",
    subcategories: [
      { id: 31, name: "Software Development" },
      { id: 32, name: "IT Services" },
      { id: 33, name: "Web Design" },
      { id: 34, name: "Cybersecurity Firms" },
      { id: 35, name: "Tech Support" },
    ],
  },
  {
    id: 8,
    category: "Transportation",
    subcategories: [
      { id: 36, name: "Taxi Services" },
      { id: 37, name: "Logistics Companies" },
      { id: 38, name: "Auto Repair Shops" },
      { id: 39, name: "Car Rentals" },
      { id: 40, name: "Shipping Companies" },
    ],
  },
  {
    id: 9,
    category: "Hospitality",
    subcategories: [
      { id: 41, name: "Hotels" },
      { id: 42, name: "Bed & Breakfasts" },
      { id: 43, name: "Resorts" },
      { id: 44, name: "Event Venues" },
      { id: 45, name: "Travel Agencies" },
    ],
  },
  {
    id: 10,
    category: "Professional Services",
    subcategories: [
      { id: 46, name: "Legal Firms" },
      { id: 47, name: "Consulting Firms" },
      { id: 48, name: "Marketing Agencies" },
      { id: 49, name: "PR Firms" },
      { id: 50, name: "Human Resources Services" },
    ],
  },
  {
    id: 11,
    category: "Manufacturing",
    subcategories: [
      { id: 51, name: "Factories" },
      { id: 52, name: "Product Assembly" },
      { id: 53, name: "Food Production" },
      { id: 54, name: "Chemical Manufacturing" },
      { id: 55, name: "Textile Manufacturing" },
    ],
  },
  {
    id: 12,
    category: "Construction",
    subcategories: [
      { id: 56, name: "General Contractors" },
      { id: 57, name: "Electricians" },
      { id: 58, name: "Plumbers" },
      { id: 59, name: "Home Builders" },
      { id: 60, name: "Roofing Companies" },
    ],
  },
  {
    id: 13,
    category: "Arts & Entertainment",
    subcategories: [
      { id: 61, name: "Theaters" },
      { id: 62, name: "Art Galleries" },
      { id: 63, name: "Music Venues" },
      { id: 64, name: "Museums" },
      { id: 65, name: "Dance Studios" },
    ],
  },
  {
    id: 14,
    category: "Beauty & Wellness",
    subcategories: [
      { id: 66, name: "Salons" },
      { id: 67, name: "Spas" },
      { id: 68, name: "Gyms" },
      { id: 69, name: "Yoga Studios" },
      { id: 70, name: "Nutritionists" },
    ],
  },
  {
    id: 15,
    category: "Agriculture",
    subcategories: [
      { id: 71, name: "Farms" },
      { id: 72, name: "Nurseries" },
      { id: 73, name: "Agricultural Equipment Sales" },
      { id: 74, name: "Organic Food Stores" },
      { id: 75, name: "Fisheries" },
    ],
  },
  {
    id: 16,
    category: "Nonprofit",
    subcategories: [
      { id: 76, name: "Charities" },
      { id: 77, name: "Advocacy Groups" },
      { id: 78, name: "Foundations" },
      { id: 79, name: "NGOs" },
      { id: 80, name: "Community Organizations" },
    ],
  },
  {
    id: 17,
    category: "E-commerce",
    subcategories: [
      { id: 81, name: "Online Retailers" },
      { id: 82, name: "Subscription Box Services" },
      { id: 83, name: "Dropshipping Businesses" },
      { id: 84, name: "Online Marketplaces" },
      { id: 85, name: "Digital Goods" },
    ],
  },
  {
    id: 18,
    category: "Media & Communications",
    subcategories: [
      { id: 86, name: "Publishing Houses" },
      { id: 87, name: "Advertising Agencies" },
      { id: 88, name: "Broadcasting Companies" },
      { id: 89, name: "Film Production" },
      { id: 90, name: "Public Relations" },
    ],
  },
  {
    id: 19,
    category: "Automotive",
    subcategories: [
      { id: 91, name: "Car Dealerships" },
      { id: 92, name: "Auto Parts Stores" },
      { id: 93, name: "Motorcycle Shops" },
      { id: 94, name: "Car Washes" },
      { id: 95, name: "Auto Body Shops" },
    ],
  },
  {
    id: 20,
    category: "Energy",
    subcategories: [
      { id: 96, name: "Solar Power Companies" },
      { id: 97, name: "Oil & Gas Companies" },
      { id: 98, name: "Utility Providers" },
      { id: 99, name: "Renewable Energy Firms" },
      { id: 100, name: "Energy Consultants" },
    ],
  },
];
